dist: xenial
language: python
python: "3.7"
install:
  python setup.py develop
script:
  python freeze.py
deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master